title:              Jolunavi
email:              joseluisnaranjo@hotmail.es
description:        I am excited to share my thoughts and experiences with you through this blog, and I hope you will join me on this journey of self-improvement and personal growth.
author:             Jose Naranjo
baseurl:            ""
url:                "https://joseluisnaranjo.github.io"
formspree:          f/xeqwjnrl

# Social Profiles
twitter_username:   josewizky
github_username:    joseluisnaranjo
facebook_username:  jolunavi1
instagram_username:  jolunavi1
linkedin_username:  jolunavi1

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
